name: htc
channels:
- defaults
- conda-forge
dependencies:
- python=3.12
- polars
- geopandas
- folium
- black
- black-jupyter
- requests
- ipywidgets
- bokeh
- jupyter
- bokeh=2.4.3
- pip
- pip:
    - streamlit_folium

